### ISSUE TITLE
微软

### ISSUE THREAD

**Issue by xianyumol** [XokoukioX/AutoMSACC#1]
微软应该会在检测到VPN的情况下先让你进行人机验证，然后再填写生日，然后就炸了:(

**Comment by KawakazeNotFound** [comment]
VPN地区最好选择新加坡或者美国，日本也可以，其他地区没试过 这些地方顺序没问题 日本我刚刚测试了 没有问题 :D

**Comment by TomChicken-on-github** [comment]
我用的hk的IEPL专线的节点
没问题的
